### ISSUE TITLE
LLVM backend assertion seen in multiple SPEC CPU 2017 Fortran benchmarks in release_11x branch

### ISSUE THREAD

**Issue by mvinay-ctt** [flang-compiler/classic-flang-llvm-project#11]
**Test case:**
```fortran
program foo
      real(kind=8) :: val, res1, res2
      read *, val
      res1 = sin(val)
      res2 = cos(val)
      print *, res1, res2
end program foo
```

**Command:**  `flang -O1`

**Assertion:**
```
$repo/classic-flang-llvm-project/llvm/lib/IR/Type.cpp:618: static llvm::FixedVectorType* llvm::FixedVectorType::get(llvm::Type*, unsigned int): Assertion `isValidElementType(ElementType) && "Element type of a VectorType must " "be an integer, floating point, or " "pointer type."' failed.
```

**Comment by bryanpkc** [comment]
@michalpasztamobica Would you like to take a look at this?

**Comment by michalpasztamobica** [comment]
Hi @bryanpkc ,
We've discussed the matter on flang-dev list and I asked @mvinay-ctt  to report this here, so it doesn't get lost as we are currently unable to take care of the failures in SPEC CPU 2017.

**Comment by michalpasztamobica** [comment]
Hi @bryanpkc , I remember from one of the biweekly syncs, that you have put some effort into checking this issue. Thanks a lot! I was wondering if you had any progress on this so far?

**Comment by bryanpkc** [comment]
This is the LLVM IR that causes the assertion on X86:
```
  %16 = call <{double, double}> @__fd_sincos_1 (double %15), !dbg !18
  .
  .
declare <{double, double}> @__fd_sincos_1(double)
```
We don't see this on AArch64 since (IIRC) Flang still generates separate `sin` and `cos` calls on that architecture.

**Comment by shivaramaarao** [comment]
workaround is to use -fveclib=none

there are pgmath  related veclib changes added in classic-flang-llvm-project/llvm/lib/Analysis/TargetLibraryInfo.cpp. these changes are causing the assertions.

  1 diff -r lib/Analysis/TargetLibraryInfo.cpp /home/amd/cflang/classic-flang-llvm-project/llvm/lib/Analysis/TargetLibraryInfo.cpp
   2 30c30,32
   3 <                           "Intel SVML library")));
   4 ---
   5 >                           "Intel SVML library"),
   6 >                clEnumValN(TargetLibraryInfoImpl::PGMATH, "PGMATH",
   7 >                           "PGI math library")));
   8 565d566
   9 <
  10 1567a1569,2018
  11 >
  12 >   // NOTE: All routines listed here are not available on all the architectures.
  13 >   // Based on the size of vector registers available and the size of data, the
  14 >   // vector width should be chosen correctly.
  15 >   case PGMATH: {
  16 >     const VecDesc VecFuncs[] = {
  17 >         {"__fd_sin_1", "__fd_sin_2", 2},
...
