### ISSUE TITLE
Many Clang options are treated as unknown arguments in release_18x branch

### ISSUE THREAD

**Issue by shivaramaarao** [flang-compiler/classic-flang-llvm-project#181]
These options gives error when clang built through release18.x branch is used
  -mavx
  -mavx2
  -mavx512
  -mfma
  -funroll-loops
 -fno-strict-aliasing
 -mtune=core-avx2

There may be some more, but if the fix is general one, it might solve issues with other options as well.

**Comment by bryanpkc** [comment]
A possible generalized fix is to modify TableGen to treat all Clang options as Flang options, but I thought this was too permissive, and may lead to the driver listing a lot of incorrect or unsupported options. The current approach is to add the `FlangOption` visibility to specific options that we know are supported and needed by Classic Flang.

I believe that the current situation with the LLVM Flang driver (`flang-new`) is the same: 

https://flang.llvm.org/docs/FlangDriver.html#adding-new-compiler-options

**Comment by bryanpkc** [comment]
A fix has been merged. Please re-open if other Clang options are needed in the Classic Flang driver.
